#!/usr/bin/expect -f

# Variables are set staticly for testing.
set timeout 20
set ip 10.32.137.100
set user root
set password foobar
set output [open "outputfile.txt" "a+"]

send_user "\n"
send_user ">>>>>  Working on $ip @ [exec date]  <<<<<\n"
send_user "\n"

## testing with a local file
spawn ./testfile

expect "'^]'."
sleep .1;
expect   "login:"
send "$user\r"
sleep .1;
expect "Password:"
send "$password\r";
sleep .1;

expect "#";

sleep .1;

set command "cat test\r"
send "$command";

expect -re "\n(.*)~ #";
send_user "\n"
send_user "$ip;$expect_out(1,string);[exec date +%Y-%m-%d-%H%M]"

puts $output "$ip;$expect_out(1,string);[exec date +%Y-%m-%d-%H%M]"
close $output
sleep 1
send "exit\r";
#interact
